apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: tinfeh/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/dsas_patients"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dsas_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dsas_password"
            