import { useState, useEffect } from "react";
import { AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { Card, Badge, Spinner, Modal, Input, Alert, EmptyState } from "../components/UI.jsx";
import { PageHeader, PrimaryBtn, SecondaryBtn } from "../components/UI.jsx";
import { diseaseAPI, locationAPI, analyticsAPI, reportAPI, geoAPI } from "../services/api.js";

const COLORS = ["#0EA5E9","#EF4444","#14B8A6","#F59E0B","#8B5CF6","#10B981","#EC4899"];
const fmtNum = (n) => n?.toLocaleString() ?? "—";

// ── ALERTS ────────────────────────────────────────────────────
export function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("All");

  useEffect(() => {
    const load = async () => {
      const d = await analyticsAPI.getAlerts();
      setAlerts(d?.alerts || []);
      setLoading(false);
    };
    load();
    const interval = setInterval(load, 15000);
    return () => clearInterval(interval);
  }, []);

  const filtered = alerts.filter(a => filter === "All" || a.severity === filter);
  const alertBg = { CRITICAL:"bg-red-50 border-red-200", HIGH:"bg-orange-50 border-orange-200", MEDIUM:"bg-yellow-50 border-yellow-200" };

  return (
    <div className="p-6 space-y-5">
      <PageHeader title="Outbreak Alerts"
        subtitle={`${alerts.length} active signal${alerts.length!==1?"s":""} from analytics-service`}
        action={
          <div className="flex items-center gap-2 text-xs text-green-600 bg-green-50 border border-green-200 rounded-xl px-3 py-2">
            <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
            Auto-refresh every 15s
          </div>
        }
      />
      <div className="flex gap-2">
        {["All","CRITICAL","HIGH","MEDIUM"].map(s => (
          <button key={s} onClick={() => setFilter(s)}
            className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all
              ${filter===s?"bg-slate-800 text-white border-slate-800":"bg-white text-slate-600 border-slate-200 hover:bg-slate-50"}`}>
            {s}
          </button>
        ))}
      </div>
      {loading ? <Spinner /> : filtered.length === 0 ? (
        <div className="text-center py-20">
          <span className="text-5xl mb-4 block">✅</span>
          <p className="font-semibold text-slate-700">No active alerts</p>
          <p className="text-sm text-slate-400 mt-1">
            {alerts.length === 0 ? "Send cases via RabbitMQ to trigger threshold alerts" : "No alerts matching filter"}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-2 gap-4">
          {filtered.map((a, i) => (
            <Card key={i} className={`p-5 border ${alertBg[a.severity]??"border-slate-200"}`}>
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${a.severity==="CRITICAL"?"bg-red-100":"bg-orange-100"}`}>
                    <span>⚠</span>
                  </div>
                  <div>
                    <p className="font-bold text-slate-800 capitalize">{a.disease}</p>
                    <p className="text-xs text-slate-400">Auto-generated by analytics-service</p>
                  </div>
                </div>
                <Badge level={a.severity} />
              </div>
              <div className="grid grid-cols-3 gap-3 mb-4">
                <div><p className="text-xs text-slate-400">Region</p><p className="text-sm font-semibold text-slate-700">📍 {a.region}</p></div>
                <div><p className="text-xs text-slate-400">Cases</p><p className="text-sm font-semibold text-red-600">📊 {fmtNum(a.cases)}</p></div>
                <div><p className="text-xs text-slate-400">Threshold</p><p className="text-sm font-semibold text-slate-700">⚡ {a.threshold}</p></div>
              </div>
              <div className="pt-3 border-t border-slate-200">
                <p className="text-xs text-slate-500">
                  {a.cases} cases ≥ threshold of {a.threshold} — <span className="font-semibold text-slate-700">Deploy rapid response team</span>
                </p>
              </div>
            </Card>
          ))}
        </div>
      )}
      {!loading && alerts.length === 0 && (
        <Card className="p-5 border border-blue-200 bg-blue-50">
          <p className="text-sm font-semibold text-blue-700 mb-2">💡 How to trigger alerts</p>
          <p className="text-xs text-blue-600">
            Open RabbitMQ UI at http://localhost:15672 (dsas_user/dsas_password) → Exchanges → patient.exchange → Publish message with routing key "patient.case.recorded". After enough messages exceeding the threshold for a disease+region combination, alerts appear here automatically.
          </p>
        </Card>
      )}
    </div>
  );
}
export default AlertsPage
