spring.datasource.url=jdbc:postgresql://localhost:5432/dsas_db
spring.datasource.username=dsas_user
spring.datasource.password=dsas_password
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=dsas_user
spring.rabbitmq.password=dsas_password