spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dsas_patients}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dsas_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dsas_password}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:dsas_user}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:dsas_password}
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false