spring.application.name=api-gateway

server.port=8000

# Eureka Server URL
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

cors.allowed-origins=http://localhost:5173,https://dsas-app.tsqpcorporation.com



# =============================================
# Routes
# =============================================

# Auth Service - public + protected user endpoints
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth-service/**

# Test Service - public test endpoint
spring.cloud.gateway.server.webmvc.routes[1].id=test-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://TEST-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/test-service/**

# Patient Service - protected patient endpoints
spring.cloud.gateway.server.webmvc.routes[2].id=patient-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/patient-service/**

# Disease Service - protected disease endpoints
spring.cloud.gateway.server.webmvc.routes[3].id=disease-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://DISEASE-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/disease-service/**

# Location Service - protected location endpoints
spring.cloud.gateway.server.webmvc.routes[4].id=location-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/location-service/**

#Analytics Service
spring.cloud.gateway.server.webmvc.routes[5].id=analytics-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/analytics/**

# Geo Service
spring.cloud.gateway.server.webmvc.routes[6].id=geo-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://GEO-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/geo/**

#Notification Service
spring.cloud.gateway.server.webmvc.routes[7].id=notification-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/notification/**

#Report Service
spring.cloud.gateway.server.webmvc.routes[8].id=report-service
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://REPORT-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/v1/reports/**

# =============================================
# JWT - MUST match Auth Service exactly
# =============================================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=86400000 

#Prometheus Config
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}


# Global CORS for Spring Cloud Gateway MVC
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173,https://dsas-app.tsqpcorporation.com
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].exposed-headers=Authorization
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].max-age=3600