spring.application.name=api-gateway

server.port=8080

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



# ?????????????????????????????????????????????
# Routes
# ?????????????????????????????????????????????

# Auth Service ? public + protected user endpoints
# ? Correct prefix for spring-cloud-starter-gateway-server-webmvc
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth-service/**

#Patient Service ? protected patient endpoints
spring.cloud.gateway.mvc.routes[2].id=patient-service
spring.cloud.gateway.mvc.routes[2].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/patient-service/**

#Disease Service ?protected  disease endpoints
spring.cloud.gateway.mvc.routes[3].id=disease-service
spring.cloud.gateway.mvc.routes[3].uri=lb://DISEASE-SERVICE
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/disease-service

# Test Service ? public test endpoint
spring.cloud.gateway.mvc.routes[1].id=test-service
spring.cloud.gateway.mvc.routes[1].uri=lb://TEST-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/test-service/**

# ?????????????????????????????????????????????
# JWT ? MUST match Auth Service exactly
# ?????????????????????????????????????????????
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970