name: DSAS - VPA Setup and Kubenetes deploy
hosts: vps
become: true
gather_facts: true

var_files:
  - vault/secrete.yml

roles:
  - role: vps-setup
    tags: [setup,infra]

  - role: k8s-deploy
    tags: [deploy,k8s]