spring.application.name=location-service

server.port=8085

# Database configuration
spring.datasource.url=jdbc:postgresql://dsas-postgres:5432/dsas_locations
spring.datasource.username=dsas_user
spring.datasource.password=dsas_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Eureka client configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
