server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /gateway/ {
        proxy_pass http://api-gateway:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /analytics/ {
        proxy_pass http://dsas-analytics:8085/;
        proxy_set_header Host $host;
    }

    location /reports/ {
        proxy_pass http://dsas-report:8086/;
        proxy_set_header Host $host;
    }

    location /notifications/ {
        proxy_pass http://dsas-notification:8087/;
        proxy_set_header Host $host;
    }

    location /geo/ {
        proxy_pass http://dsas-geo:8088/;
        proxy_set_header Host $host;
    }
}
